# These are supported funding model platforms

custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=folke%2ewill%40gmail%2ecom&lc=US&item_name=AviTab&no_note=0&cn=Message%20to%20the%20developer%3a&no_shipping=1&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted', Paypal.com]

